---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
  name: config
  apiServer:
    extraArgs:
      "enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
  controllerManager:
    extraArgs:
      - name: "cluster-signing-key-file"
        value: "/etc/kubernetes/pki/ca.key"
      - name: "cluster-signing-cert-file"
        value: "/etc/kubernetes/pki/ca.crt"
nodes:
- role: control-plane
