---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    mutateme: enabled
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  namespace: demo
spec:
  containers:
  - command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    image: busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always